Repository Cambridge-ICCS/intermediate-git-iccs-summer-school-2024, pull requests merged in 2024-06, with the labels that each got.

#5 Add TDD framework, description and usage instructions
  README.md
  maths.py
  requirements.txt
  test_maths.py
Labels: documentation, enhancement

#9 Implement `equation_of_line` and setup CI testing
  .github/workflows/test_suite.yml
  maths.py
Labels: enhancement

#17 docs: add slides link to README
  README.md
Labels: documentation
